# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/home/mrsang/torob_ws/src/adhoc_communication/msg/ExpAuction.msg;/home/mrsang/torob_ws/src/adhoc_communication/msg/ExpAuctionElement.msg;/home/mrsang/torob_ws/src/adhoc_communication/msg/ExpFrontierElement.msg;/home/mrsang/torob_ws/src/adhoc_communication/msg/MmControl.msg;/home/mrsang/torob_ws/src/adhoc_communication/msg/MmMapUpdate.msg;/home/mrsang/torob_ws/src/adhoc_communication/msg/MmRobotPosition.msg;/home/mrsang/torob_ws/src/adhoc_communication/msg/ExpCluster.msg;/home/mrsang/torob_ws/src/adhoc_communication/msg/ExpClusterElement.msg;/home/mrsang/torob_ws/src/adhoc_communication/msg/ExpFrontier.msg;/home/mrsang/torob_ws/src/adhoc_communication/msg/MmListOfPoints.msg;/home/mrsang/torob_ws/src/adhoc_communication/msg/MmPoint.msg;/home/mrsang/torob_ws/src/adhoc_communication/msg/RecvString.msg;/home/mrsang/torob_ws/src/adhoc_communication/msg/CMgrDimensions.msg;/home/mrsang/torob_ws/src/adhoc_communication/msg/CMgrRobotUpdate.msg"
services_str = "/home/mrsang/torob_ws/src/adhoc_communication/srv/ChangeMCMembership.srv;/home/mrsang/torob_ws/src/adhoc_communication/srv/SendExpAuction.srv;/home/mrsang/torob_ws/src/adhoc_communication/srv/SendExpFrontier.srv;/home/mrsang/torob_ws/src/adhoc_communication/srv/SendMmMapUpdate.srv;/home/mrsang/torob_ws/src/adhoc_communication/srv/SendMmRobotPosition.srv;/home/mrsang/torob_ws/src/adhoc_communication/srv/SendQuaternion.srv;/home/mrsang/torob_ws/src/adhoc_communication/srv/GetNeighbors.srv;/home/mrsang/torob_ws/src/adhoc_communication/srv/SendExpCluster.srv;/home/mrsang/torob_ws/src/adhoc_communication/srv/SendMmControl.srv;/home/mrsang/torob_ws/src/adhoc_communication/srv/SendMmPoint.srv;/home/mrsang/torob_ws/src/adhoc_communication/srv/SendOccupancyGrid.srv;/home/mrsang/torob_ws/src/adhoc_communication/srv/SendString.srv;/home/mrsang/torob_ws/src/adhoc_communication/srv/GetGroupState.srv;/home/mrsang/torob_ws/src/adhoc_communication/srv/SendTwist.srv;/home/mrsang/torob_ws/src/adhoc_communication/srv/SendCMgrRobotUpdate.srv;/home/mrsang/torob_ws/src/adhoc_communication/srv/ShutDown.srv;/home/mrsang/torob_ws/src/adhoc_communication/srv/BroadcastCMgrRobotUpdate.srv;/home/mrsang/torob_ws/src/adhoc_communication/srv/BroadcastString.srv"
pkg_name = "adhoc_communication"
dependencies_str = "std_msgs;nav_msgs;geometry_msgs"
langs = "gencpp;geneus;genlisp;gennodejs;genpy"
dep_include_paths_str = "adhoc_communication;/home/mrsang/torob_ws/src/adhoc_communication/msg;std_msgs;/opt/ros/kinetic/share/std_msgs/cmake/../msg;nav_msgs;/opt/ros/kinetic/share/nav_msgs/cmake/../msg;geometry_msgs;/opt/ros/kinetic/share/geometry_msgs/cmake/../msg;actionlib_msgs;/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg"
PYTHON_EXECUTABLE = "/usr/bin/python"
package_has_static_sources = '' == 'TRUE'
genmsg_check_deps_script = "/opt/ros/kinetic/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
